services:

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      BACKEND_PORT: 3001
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
